# export.py
"""
Export utility module for Advanced Port Scanner.
Generates CSV, JSON, and formatted Text reports of scan results.
"""

import csv
import json
import os

def export_to_json(filepath, target_info, results):
    """
    Exports results as a structured JSON file.
    """
    data = {
        "target": target_info,
        "results": results
    }
    try:
        with open(filepath, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=4)
        return True, f"Successfully exported to {os.path.basename(filepath)}"
    except Exception as e:
        return False, str(e)

def export_to_csv(filepath, target_info, results):
    """
    Exports results as a CSV file.
    """
    try:
        with open(filepath, "w", newline="", encoding="utf-8") as f:
            writer = csv.writer(f)
            # Metadata
            writer.writerow(["Target IP", target_info.get("ip", "")])
            writer.writerow(["Target Host", target_info.get("host", "")])
            writer.writerow(["Scan Time", target_info.get("timestamp", "")])
            writer.writerow([])
            
            # Headers
            writer.writerow(["Port", "Protocol", "State", "Service", "Version", "OS Heuristic", "Banner"])
            
            # Data
            for r in results:
                writer.writerow([
                    r.get("port", ""),
                    r.get("protocol", ""),
                    r.get("state", ""),
                    r.get("service", ""),
                    r.get("version", ""),
                    r.get("os", ""),
                    r.get("banner", "").replace("\n", " ").replace("\r", "")
                ])
        return True, f"Successfully exported to {os.path.basename(filepath)}"
    except Exception as e:
        return False, str(e)

def export_to_txt(filepath, target_info, results):
    """
    Exports results as a clean, human-readable Text file.
    """
    try:
        with open(filepath, "w", encoding="utf-8") as f:
            f.write("="*60 + "\n")
            f.write("             ADVANCED PORT SCANNER REPORT\n")
            f.write("="*60 + "\n")
            f.write(f"Target IP:   {target_info.get('ip', '')}\n")
            f.write(f"Target Host: {target_info.get('host', '')}\n")
            f.write(f"Scan Date:   {target_info.get('timestamp', '')}\n")
            f.write(f"Duration:    {target_info.get('duration', '')} seconds\n")
            f.write(f"Protocol:    {target_info.get('protocol', '')}\n")
            f.write("="*60 + "\n\n")
            
            f.write(f"{'PORT':<8} {'PROTO':<6} {'STATE':<8} {'SERVICE':<15} {'VERSION':<20} {'OS':<15}\n")
            f.write("-" * 75 + "\n")
            for r in results:
                f.write(
                    f"{r.get('port', ''):<8} "
                    f"{r.get('protocol', '').upper():<6} "
                    f"{r.get('state', ''):<8} "
                    f"{r.get('service', ''):<15} "
                    f"{r.get('version', ''):<20} "
                    f"{r.get('os', ''):<15}\n"
                )
                if r.get('banner'):
                    clean_banner = r.get('banner').strip().replace('\n', '\n      | ')
                    f.write(f"   └─ Banner: {clean_banner}\n")
            
            f.write("\n" + "="*60 + "\n")
            f.write("Report generated by Advanced Port Scanner.\n")
            f.write("="*60 + "\n")
        return True, f"Successfully exported to {os.path.basename(filepath)}"
    except Exception as e:
        return False, str(e)
